// ── Admin Clients Data ────────────────────────────────────────────────────────
// Full client data with repo info, health status, and metadata
// Used by /admin page

export type ClientStatus = 'live' | 'deploying' | 'offline' | 'paying'
export type ClientType = 'demo' | 'showcase' | 'paying' | 'prospect'

export interface Client {
  id: string
  name: string
  url: string
  rubro: string
  desc: string
  slug: string
  status: ClientStatus
  type: ClientType
  reviews?: number
  leads?: number
  plan?: string
  repoOwner?: string
  repoName?: string
  githubUrl?: string
  lastCheck?: string
  responseTime?: number
  email?: string
  phone?: string
  notes?: string
  order: number
}

export const ADMIN_CLIENTS: Client[] = [
  // ── PAYING CLIENTS ──
  {
    id: 'shine-nails',
    name: 'Shine Nails',
    url: 'https://shinenails.com.py',
    rubro: 'Uñas / Nails',
    desc: 'Nails studio Celeste — 287 reseñas 4.9★ Google',
    slug: 'shine-nails',
    status: 'paying',
    type: 'paying',
    reviews: 287,
    leads: 47,
    plan: 'Profesional',
    repoOwner: 'Ai-Whisperers',
    repoName: 'shine-nails',
    githubUrl: 'https://github.com/Ai-Whisperers/shine-nails',
    email: 'celeste@shinenails.com.py',
    phone: '+595981000001',
    order: 1,
  },
  {
    id: 'nde-barba',
    name: 'Nde Barba',
    url: 'https://ndebarba.com.py',
    rubro: 'Barbería',
    desc: 'Barbería 4.8 estrellas — leads confirmados',
    slug: 'nde-barba',
    status: 'paying',
    type: 'paying',
    reviews: 180,
    leads: 32,
    plan: 'Crecimiento',
    repoOwner: 'Ai-Whisperers',
    repoName: 'nde-barba',
    githubUrl: 'https://github.com/Ai-Whisperers/nde-barba',
    email: 'ndebarba@gmail.com',
    phone: '+595981000002',
    order: 2,
  },
  {
    id: 'portas-barber',
    name: 'Portas Barber',
    url: 'https://portasbarber.com.py',
    rubro: 'Barbería',
    desc: 'Barbería premium en Asunción — 162 reseñas Google',
    slug: 'portas-barber',
    status: 'paying',
    type: 'paying',
    reviews: 162,
    leads: 28,
    plan: 'Crecimiento',
    repoOwner: 'Ai-Whisperers',
    repoName: 'portas-barber',
    githubUrl: 'https://github.com/Ai-Whisperers/portas-barber',
    email: 'portasbarber@gmail.com',
    phone: '+595981000003',
    order: 3,
  },
  {
    id: 'xxgym',
    name: 'XXGym',
    url: 'https://xxgym.com.py',
    rubro: 'Gimnasio',
    desc: 'Gimnasio en Fernando de la Mora — leads activos',
    slug: 'xxgym',
    status: 'paying',
    type: 'paying',
    reviews: 94,
    leads: 61,
    plan: 'Profesional',
    repoOwner: 'Ai-Whisperers',
    repoName: 'xxgym',
    githubUrl: 'https://github.com/Ai-Whisperers/xxgym',
    email: 'xxgym@gmail.com',
    phone: '+595981000004',
    order: 4,
  },
  // ── SHOWCASE STANDARDS ──
  {
    id: 'mantraspa',
    name: 'Mantra Spa',
    url: 'https://mantraspa.paragu-ai.com',
    rubro: 'Spa & Wellness',
    desc: 'Masajes, tratamientos faciales y bienestar',
    slug: 'mantraspa',
    status: 'live',
    type: 'showcase',
    reviews: 927,
    leads: 2393,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'mantra-spa',
    githubUrl: 'https://github.com/Ai-Whisperers/mantra-spa',
    order: 5,
  },
  {
    id: 'bichosgym',
    name: 'Bichos Gym',
    url: 'https://bichosgym.paragu-ai.com',
    rubro: 'Gimnasio / Fitness',
    desc: 'Entrenamiento funcional y crossfit',
    slug: 'bichosgym',
    status: 'live',
    type: 'showcase',
    reviews: 341,
    leads: 1087,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'bichosgym',
    githubUrl: 'https://github.com/Ai-Whisperers/bichosgym',
    order: 6,
  },
  {
    id: 'nexa',
    name: 'Nexa Paraguay',
    url: 'https://nexa.paragu-ai.com',
    rubro: 'Reubicación',
    desc: 'Programa de reubicación para europeos (4 idiomas)',
    slug: 'nexa',
    status: 'live',
    type: 'showcase',
    reviews: 0,
    leads: 0,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'nexa-paraguay',
    githubUrl: 'https://github.com/Ai-Whisperers/nexa-paraguay',
    order: 7,
  },
  {
    id: 'superspuma',
    name: 'Superspuma',
    url: 'https://superspuma.paragu-ai.com',
    rubro: 'Indumentaria',
    desc: 'Ropa oversize y streetwear paraguayo',
    slug: 'superspuma',
    status: 'live',
    type: 'showcase',
    reviews: 0,
    leads: 0,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'superspuma',
    githubUrl: 'https://github.com/Ai-Whisperers/superspuma',
    order: 8,
  },
  {
    id: 'magnolia-flower',
    name: 'Magnolia Flower',
    url: 'https://magnolia-flower.paragu-ai.com',
    rubro: 'Florería',
    desc: 'Flores y decoración de eventos',
    slug: 'magnolia-flower',
    status: 'live',
    type: 'showcase',
    reviews: 0,
    leads: 0,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'magnolia-flower',
    githubUrl: 'https://github.com/Ai-Whisperers/magnolia-flower',
    order: 9,
  },
  {
    id: 'depiflash',
    name: 'DepiFlash',
    url: 'https://depiflash.paragu-ai.com',
    rubro: 'Depilación',
    desc: 'Depilación láser IPL a domicilio',
    slug: 'depiflash',
    status: 'live',
    type: 'showcase',
    reviews: 0,
    leads: 0,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'depiflash',
    githubUrl: 'https://github.com/Ai-Whisperers/depiflash',
    order: 10,
  },
  // ── DEMO SITES ──
  {
    id: 'hidrobaby-spa',
    name: 'HidroBaby Spa',
    url: 'https://hidrobaby-spa.paragu-ai.com',
    rubro: 'Spa / Baby Spa',
    desc: 'Baby spa, pediátrico y prenatal — 3 sucursales en Paraguay',
    slug: 'hidrobaby-spa',
    status: 'live',
    type: 'demo',
    reviews: 112,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'hidrobaby-spa',
    githubUrl: 'https://github.com/Ai-Whisperers/hidrobaby-spa',
    order: 11,
  },
  {
    id: 'cronos-academy',
    name: 'Cronos Academy',
    url: 'https://cronos-academy.paragu-ai.com',
    rubro: 'Gimnasio / Crossfit',
    desc: 'Academia crossfit y functional training en San Lorenzo',
    slug: 'cronos-academy',
    status: 'live',
    type: 'demo',
    reviews: 203,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'cronos-academy',
    githubUrl: 'https://github.com/Ai-Whisperers/cronos-academy',
    order: 12,
  },
  {
    id: 'estudio-medieval',
    name: 'Estudio Medieval',
    url: 'https://estudio-medieval.paragu-ai.com',
    rubro: 'Barbería',
    desc: 'Barbería vintage con 388+ reseñas Google',
    slug: 'estudio-medieval',
    status: 'live',
    type: 'demo',
    reviews: 388,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'estudio-medieval',
    githubUrl: 'https://github.com/Ai-Whisperers/estudio-medieval',
    order: 13,
  },
  {
    id: 'leticia-carballo',
    name: 'Leticia Carballo',
    url: 'https://leticia-carballo.paragu-ai.com',
    rubro: 'Hair & Makeup',
    desc: 'Estudio hair & makeup con 206 reseñas',
    slug: 'leticia-carballo',
    status: 'live',
    type: 'demo',
    reviews: 206,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'leticia-carballo',
    githubUrl: 'https://github.com/Ai-Whisperers/leticia-carballo',
    order: 14,
  },
  {
    id: 'nutrifit-spa',
    name: 'Nutrifit Spa',
    url: 'https://nutrifit-spa.paragu-ai.com',
    rubro: 'Spa / Nutrición',
    desc: 'Spa y nutrición integral — 233 reseñas Google',
    slug: 'nutrifit-spa',
    status: 'live',
    type: 'demo',
    reviews: 233,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'nutrifit-spa',
    githubUrl: 'https://github.com/Ai-Whisperers/nutrifit-spa',
    order: 15,
  },
  {
    id: 'clau-bellino',
    name: 'Clau Bellino',
    url: 'https://clau-bellino.paragu-ai.com',
    rubro: 'Estética Facial',
    desc: 'Tratamientos faciales y depilación láser',
    slug: 'clau-bellino',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'clau-bellino',
    githubUrl: 'https://github.com/Ai-Whisperers/clau-bellino',
    order: 16,
  },
  {
    id: 'barbye-nails',
    name: 'Barbye Nails',
    url: 'https://barbye-nails.paragu-ai.com',
    rubro: 'Uñas / Nail Art',
    desc: 'Nail art y manicuria en Fernando de la Mora',
    slug: 'barbye-nails',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'barbye-nails',
    githubUrl: 'https://github.com/Ai-Whisperers/barbye-nails',
    order: 17,
  },
  {
    id: 'arnos-barber-shop',
    name: "Arno's Barber Shop",
    url: 'https://arnos-barber-shop.paragu-ai.com',
    rubro: 'Barbería',
    desc: 'Barbería moderna en Fernando de la Mora',
    slug: 'arnos-barber-shop',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'arnos-barber-shop',
    githubUrl: 'https://github.com/Ai-Whisperers/arnos-barber-shop',
    order: 18,
  },
  {
    id: 'avani-belleza',
    name: 'Avani Belleza',
    url: 'https://avani-belleza.paragu-ai.com',
    rubro: 'Belleza Integral',
    desc: 'Salón de belleza, maquillaje y peinado',
    slug: 'avani-belleza',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'avani-belleza',
    githubUrl: 'https://github.com/Ai-Whisperers/avani-belleza',
    order: 19,
  },
  {
    id: 'viviesteticpy',
    name: 'Viviesteticpy',
    url: 'https://viviesteticpy.paragu-ai.com',
    rubro: 'Belleza / Microblading',
    desc: 'Microblading, pestañas y estética avanzada',
    slug: 'viviesteticpy',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'viviesteticpy',
    githubUrl: 'https://github.com/Ai-Whisperers/viviesteticpy',
    order: 20,
  },
  {
    id: 'scott-tatuajes',
    name: 'Scott Tatuajes',
    url: 'https://scott-tatuajes.paragu-ai.com',
    rubro: 'Tatuajes',
    desc: 'Estudio de tatuajes realista y cover-up',
    slug: 'scott-tatuajes',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'scott-tatuajes',
    githubUrl: 'https://github.com/Ai-Whisperers/scott-tatuajes',
    order: 21,
  },
  {
    id: 'woman-cosmeticos',
    name: 'Woman Cosméticos',
    url: 'https://woman-cosmeticos.paragu-ai.com',
    rubro: 'Cosméticos',
    desc: 'Cosméticos y cuidado personal',
    slug: 'woman-cosmeticos',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'woman-cosmeticos',
    githubUrl: 'https://github.com/Ai-Whisperers/woman-cosmeticos',
    order: 22,
  },
  {
    id: 'lele-ferreira',
    name: 'Lele Ferreira',
    url: 'https://lele-ferreira.paragu-ai.com',
    rubro: 'Maquillaje',
    desc: 'Maquillaje social y de novia',
    slug: 'lele-ferreira',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'lele-ferreira',
    githubUrl: 'https://github.com/Ai-Whisperers/lele-ferreira',
    order: 23,
  },
  {
    id: 'magnolia-peluqueria',
    name: 'Magnolia Peluquería',
    url: 'https://magnolia-peluqueria.paragu-ai.com',
    rubro: 'Peluquería',
    desc: 'Peluquería integral en barrio Oporto',
    slug: 'magnolia-peluqueria',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'magnolia-peluqueria',
    githubUrl: 'https://github.com/Ai-Whisperers/magnolia-peluqueria',
    order: 24,
  },
  {
    id: 'reinadecopas',
    name: 'Reinadecopas',
    url: 'https://reinadecopas.paragu-ai.com',
    rubro: 'Cerveza Artesanal',
    desc: 'Tienda online de cerveza artesanal paraguaya',
    slug: 'reinadecopas',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'reinadecopas',
    githubUrl: 'https://github.com/Ai-Whisperers/reinadecopas',
    order: 25,
  },
  {
    id: 'fun4me',
    name: 'Fun4Me',
    url: 'https://fun4me.paragu-ai.com',
    rubro: 'Eventos / Kids',
    desc: 'Eventos infantiles y cumpleaños',
    slug: 'fun4me',
    status: 'live',
    type: 'demo',
    reviews: 0,
    leads: 0,
    plan: 'demo',
    repoOwner: 'Ai-Whisperers',
    repoName: 'fun4me',
    githubUrl: 'https://github.com/Ai-Whisperers/fun4me',
    order: 26,
  },
  // ── PROSPECTS / UNDEPLOYED ──
  {
    id: 'mantra-spa-repo',
    name: 'Mantra Spa (repo)',
    url: '/root/mantra-spa',
    rubro: 'Spa & Wellness',
    desc: 'Repo local — no deployado aún',
    slug: 'mantra-spa',
    status: 'deploying',
    type: 'prospect',
    reviews: 0,
    leads: 0,
    plan: 'pending',
    repoOwner: 'Ai-Whisperers',
    repoName: 'mantra-spa',
    githubUrl: 'https://github.com/Ai-Whisperers/mantra-spa',
    order: 27,
  },
  {
    id: 'maiyu-atelier',
    name: 'Maiyu Atelier',
    url: '/root/maiyu-atelier',
    rubro: 'Indumentaria',
    desc: 'Repo local — no deployado',
    slug: 'maiyu-atelier',
    status: 'offline',
    type: 'prospect',
    reviews: 0,
    leads: 0,
    plan: 'unknown',
    repoOwner: 'Ai-Whisperers',
    repoName: 'maiyu-atelier',
    githubUrl: 'https://github.com/Ai-Whisperers/maiyu-atelier',
    order: 28,
  },
  {
    id: 'maskarada',
    name: 'Maskarada',
    url: '/root/maskarada',
    rubro: 'Indumentaria',
    desc: 'Repo local — no deployado',
    slug: 'maskarada',
    status: 'offline',
    type: 'prospect',
    reviews: 0,
    leads: 0,
    plan: 'unknown',
    repoOwner: 'Ai-Whisperers',
    repoName: 'maskarada',
    githubUrl: 'https://github.com/Ai-Whisperers/maskarada',
    order: 29,
  },
  {
    id: 'nexa-paraguay-repo',
    name: 'Nexa Paraguay (repo)',
    url: '/root/nexa-paraguay',
    rubro: 'Reubicación',
    desc: 'Repo local con deploy activo en nexa.paragu-ai.com',
    slug: 'nexa',
    status: 'live',
    type: 'showcase',
    reviews: 0,
    leads: 0,
    plan: 'showcase',
    repoOwner: 'Ai-Whisperers',
    repoName: 'nexa-paraguay',
    githubUrl: 'https://github.com/Ai-Whisperers/nexa-paraguay',
    order: 30,
  },
]

// Stats summary
export const STATS = {
  total: ADMIN_CLIENTS.length,
  live: ADMIN_CLIENTS.filter(c => c.status === 'live').length,
  paying: ADMIN_CLIENTS.filter(c => c.status === 'paying').length,
  deploying: ADMIN_CLIENTS.filter(c => c.status === 'deploying').length,
  offline: ADMIN_CLIENTS.filter(c => c.status === 'offline').length,
  totalReviews: ADMIN_CLIENTS.reduce((sum, c) => sum + (c.reviews || 0), 0),
  totalLeads: ADMIN_CLIENTS.reduce((sum, c) => sum + (c.leads || 0), 0),
  byRubro: [...new Set(ADMIN_CLIENTS.map(c => c.rubro))],
}

// Rubros for filtering
export const RUBROS = [...new Set(ADMIN_CLIENTS.map(c => c.rubro))].sort()

// Admin credentials (change PASSWORD after first login)
export const ADMIN_PASSWORD = 'paraguai2026'